### ISSUE TITLE
Gally does not scope building / testing with the matching tag

### ISSUE THREAD

**Issue by Elpayet** [missena-corp/gally#34]
CURRENT BEHAVIOUR:

Working on monorepo, containing projects A, B, C,

when having changes in A & B,
if I version bump and tag A & B, 
gally tests A & B for tag on A, and A & B (again) for tag on B.

WISHED BEHAVIOUR:

[...]
gally tests A for tag on A, and B for tag on B.

---

Would it be possible to scope project building and testing (possibly let a parameter control this behaviour if this is a feature) to the tagged project

our monorepo contains more than 10 projects. Doing a transversal change on each one of them in the same PR is a PITA.

Thanks in advance.

**Comment by gregoryguillou** [comment]
This should have been fixed by #36 ; v0.0.26 includes the `-p` flog with `gally run`for that purpose
